name: Deploy Terraform

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      # Inject Secrets into Environment Variables
      - name: Set Environment Variables
        env:
          RDS_USERNAME: ${{ secrets.RDS_USERNAME }}
          RDS_PASSWORD: ${{ secrets.RDS_PASSWORD }}
        run: echo "Secrets loaded into environment variables"

      # Terraform Init
      - name: Terraform Init
        run: terraform init

      # Terraform Plan
      - name: Terraform Plan
        run: terraform plan \
          -var "rds_username=${{ secrets.RDS_USERNAME }}" \
          -var "rds_password=${{ secrets.RDS_PASSWORD }}"

      # Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve \
          -var "rds_username=${{ secrets.RDS_USERNAME }}" \
          -var "rds_password=${{ secrets.RDS_PASSWORD }}"
