name: Deploy Terraform

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest # Required because GitHub Actions doesn't directly support Alpine
    container:
      image: alpine:3.19 # Use Alpine 3.19
    steps:
      # 1. Install Required Tools
      - name: Install Required Tools
        run: |
          apk add --no-cache \
            curl \
            bash \
            git \
            openssh \
            aws-cli \
            python3 \
            py3-pip \
            terraform

          terraform -v
          aws --version

      # 2. Checkout Repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # 3. Configure AWS Credentials
      - name: Configure AWS Credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region us-east-1

      # 4. Initialize Terraform
      - name: Terraform Init
        working-directory: ./iac
        run: terraform init

      # 5. Terraform Plan
      - name: Terraform Plan
        working-directory: ./iac
        run: |
          terraform plan \
            -var="rds_username=${{ secrets.RDS_USERNAME }}" \
            -var="rds_password=${{ secrets.RDS_PASSWORD }}"

      # 6. Terraform Apply
      - name: Terraform Apply
        working-directory: ./iac
        run: |
          terraform apply -auto-approve \
            -var="rds_username=${{ secrets.RDS_USERNAME }}" \
            -var="rds_password=${{ secrets.RDS_PASSWORD }}"
