name: Deploy Terraform

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      # Inject Secrets into Environment Variables
      - name: Set Environment Variables
        env:
          RDS_USERNAME: ${{ secrets.RDS_USERNAME }}
          RDS_PASSWORD: ${{ secrets.RDS_PASSWORD }}
        run: echo "Secrets loaded into environment variables"
    

      # Terraform Init
      - name: Terraform Init
        run: |
          cd iac
          terraform init

      # Terraform Plan
      - name: Terraform Plan
        run: |
          cd iac
          terraform plan \
          -var "rds_username=${{ secrets.RDS_USERNAME }}" \
          -var "rds_password=${{ secrets.RDS_PASSWORD }}"

      # Terraform Apply
      - name: Terraform Apply
        run: |
          cd iac
          terraform apply -auto-approve \
          -var "rds_username=${{ secrets.RDS_USERNAME }}" \
          -var "rds_password=${{ secrets.RDS_PASSWORD }}"

