name: Deploy Terraform

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest # Using Ubuntu instead of Alpine

    steps:
      # 1. Install Required Tools
      - name: Install Required Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            curl \
            bash \
            git \
            openssh-client \
            python3 \
            python3-pip \
            unzip \
            software-properties-common

          # Install AWS CLI from official URL
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install

          # Install Terraform from HashiCorp repository
          sudo apt-add-repository -y ppa:hashicorp/ppa
          sudo apt-get update
          sudo apt-get install -y terraform

          # Confirm installations
          terraform -v
          aws --version

      # 2. Checkout Repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # 3. Configure AWS Credentials
      - name: Configure AWS Credentials
        run: |
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
          echo "[default]" > ~/.aws/config
          echo "region = us-east-1" >> ~/.aws/config

      # 4. Initialize Terraform
      - name: Terraform Init
        working-directory: ./iac
        run: terraform init

      # 5. Terraform Plan
      - name: Terraform Plan
        working-directory: ./iac
        run: |
          terraform plan \
            -var="rds_username=${{ secrets.RDS_USERNAME }}" \
            -var="rds_password=${{ secrets.RDS_PASSWORD }}"

      # 6. Terraform Apply
      - name: Terraform Apply
        working-directory: ./iac
        run: |
          terraform apply -auto-approve \
            -var="rds_username=${{ secrets.RDS_USERNAME }}" \
            -var="rds_password=${{ secrets.RDS_PASSWORD }}"
