name: Deploy Terraform

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init (Backend Setup)
        run: |
          cd backend_setup
          terraform init

      - name: Terraform Apply (Backend Setup)
        run: |
          cd backend_setup
          terraform apply -auto-approve

      - name: Terraform Init (Main)
        run: |
          cd iac
          terraform init

      - name: Terraform Plan
        run: |
          cd iac
          terraform plan \
          -var "rds_username=${{ secrets.RDS_USERNAME }}" \
          -var "rds_password=${{ secrets.RDS_PASSWORD }}"

      - name: Terraform Apply
        run: |
          cd iac
          terraform apply -auto-approve \
          -var "rds_username=${{ secrets.RDS_USERNAME }}" \
          -var "rds_password=${{ secrets.RDS_PASSWORD }}"
